### PR TITLE
Decouple xk6 lint checkers to ensure independence

### LINKED ISSUE #305: build check fails
How to reproduce:

From the directory of the extension (tested with `github.com/mostafa/xk6-kafka`)
```sh 
xk6 lint --enable-only build

k6 extension compliance

✗ build               
  missing go.mod

rest of output ommited
```

But `xk6 lint --enable-only` module works
```
k6 extension compliance

✔ module              
  found `github.com/mostafa/xk6-kafka` as go module
```

Also, `xk6 build` works
```
xk6 build --with github.com/mostafa/xk6-kafka=.
:43PM INF Building new k6 binary (native)

....

xk6 has now produced a new k6 binary which may be different than the command on your system path!
Be sure to run './k6 run <SCRIPT_NAME>' from the '/tmp/tmp.xnhZZKIEkL' directory.
```

### LINKED ISSUE #310: Decouple xk6 lint checkers to ensure independence
The design of the `xk6 lint` command aims to allow users to run specific checkers independently using flags like `--enable-only`. However, some checkers currently rely on the side effects or internal results generated by other checkers (e.g., determining the exact location of the `go.mod` file).

This creates implicit dependencies between the checkers, which violates the principle of modularity and breaks the intended functionality of selective checking.

### Expected Behavior

A user should be able to run any single checker successfully using the `--enable-only` flag, without needing to explicitly enable any other checker that might supply necessary environmental context (like file paths or configuration data).

For example, running a checker that requires the `go.mod` file should work even if the checker responsible for finding that file is disabled.

### Actual Behavior

Checkers often fail or run incorrectly when executed in isolation (via `--enable-only`), as they depend on the state or results calculated by another, implicitly required checker. This forces users to enable more checkers than necessary, or prevents them from isolating specific checks during development.

### Root Cause Analysis

The shared environmental setup or context (such as the base directory or the location of critical project files like `go.mod`) is not being calculated once and passed explicitly to all checkers. Instead, this information is being derived as a side effect within one checker and then relied upon by others.

### Proposed Solution

Extract Locator Logic to Utilities: The logic responsible for locating critical project files (e.g., finding the `go.mod` file) must be extracted into dedicated, reusable utility functions.

### PR DESCRIPTION
**Pull request by szkiba**
Closes #310 
Closes #305

### CODE REVIEW

File: internal/lint/spy.go [hunk 1]
```diff
@@ -0,0 +1,191 @@
...
+	"os/exec"
+	"path/filepath"
+	"regexp"
+
+	"golang.org/x/mod/modfile"
+)
+
+type spyKey struct{}
+
+type spy struct {
```
Comment (pablochacin) [inline internal/lint/spy.go]: I would prefer a name that reflects the information contained and/or the purpose of this strucutre. 
Is this a linter context?

File: internal/lint/checker_build.go [hunk 2]
```diff
@@ -0,0 +1,25 @@
+package lint
+
+import (
+	"context"
+)
+
+func checkerBuild(ctx context.Context, _ string) *checkResult {
```
Comment (pablochacin) [inline internal/lint/checker_build.go]: I find this name confusing. It is called `checkerBuild` but it seems to be checking only the module path.

**Review by pablochacin — COMMENTED** [review]
I like the approach of using a context for passig information between checkers instead of having a dependency between them, but as detailed in my comments there are two things that make it hard to understand:
- the name of `spy` does not conveny much information
- building the binary in this "spy" instead of in the build checker is unexpected and I'm not enterely sure is it necessary.

File: internal/lint/spy.go (hunk 1 above)
Comment (szkiba) [reply internal/lint/spy.go]: In the meantime I renamed it to `state`

File: internal/lint/checker_build.go (hunk 2 above)
Comment (szkiba) [reply internal/lint/checker_build.go]: The concept is:
- the controller uses `state` optionally, not required
- the controller never modifies `state`
- the state "getter" functions either return a cached value or generate the value on the fly, cache it, and return it

The consequence of this is that the "build" checker "only" gets the path of the built exe.

**Comment by szkiba** [comment]
> I like the approach of using a context for passig information between checkers instead of having a dependency between them, but as detailed in my comments there are two things that make it hard to understand:
> 
>     * the name of `spy` does not conveny much information
> 
>     * building the binary in this "spy" instead of in the build checker is unexpected and I'm not enterely sure is it necessary.

In the mean time `spy` has been renamed to `state`.

The concept is:
- the checker uses `state` optionally, it is not mandatory
- the checker never modifies `state`
- the state "getter" functions either return a cached value or generate the value on the fly, cache it and return it

File: internal/lint/checker_build.go (hunk 2 above)
Comment (pablochacin) [reply internal/lint/checker_build.go]: I think the concept is clear, but I still find it confusing that the build check is not building but asking for th exec path (that implicitly builds the binary). I wonder if, for this particular case, the build artifact has to be shared in the context?
