### PR TITLE
Template-specific files are excluded during the xk6 new command

### LINKED ISSUE #342: Support exclusion list for `xk6 new` template copy
The current behavior of the `xk6 new` command is to copy **all** files from the template repository (e.g., `github.com/grafana/xk6-example`) into the newly created extension directory, with the sole exception of the `.git` directory.

This causes unnecessary files that are relevant only to the **template repository's maintenance** (like `CODEOWNERS` or configuration files for dependency management) to be copied into every new extension, which is typically undesirable.

## Proposal

Implement an **exception list** feature for the `xk6 new` command. This list would specify files and directories within the template that should **not** be copied into the new extension directory.

This functionality would generalize the current exclusion of the `.git` directory.

## Additional context

The initial contents of this exclusion list should include:

* `.git`
* `CODEOWNERS`
* `renovate.json`

### PR DESCRIPTION
**Pull request by szkiba**
Closes #342

### CODE REVIEW

File: internal/scaffold/scaffold.go [hunk 1]
```diff
@@ -92,6 +92,17 @@ func checkout(repo *git.Repository, name plumbing.ReferenceName) error {
 	return wt.Checkout(&git.CheckoutOptions{Branch: name})
 }
 
+func cleanup(dir string) error {
+	special := []string{".git", "CODEOWNERS", "renovate.json"}
```
Comment (pablochacin) [inline internal/scaffold/scaffold.go]: nitpick: I think `exclude_list` is a more descriptive name.
