### PR TITLE
Correctly log k6 version during build`

### LINKED ISSUE #52: Warn when old k6 version is used
After https://github.com/grafana/xk6/pull/44, xk6 will not always try to use the latest k6 version to build the binary, it will instead use the one specified in the extensions' go.mod file(s). However, as [this forum thread has shown](https://community.k6.io/t/goerror-unknown-module-k6-execution/5011), this can cause problems for unmaintained extensions, when users expect to be able to access newer k6 built-in APIs.

So, it would be nice if xk6 emits a warning when we are going to use an older version of k6. It seems like we can do it by running `go list -m -json -u -mod=readonly go.k6.io/k6` for the repo, it will produce something like this:
```
{
	"Path": "go.k6.io/k6",
	"Version": "v0.33.1-0.20210825161650-c932a28ff940",
	"Time": "2021-08-25T16:16:50Z",
	"Update": {
		"Path": "go.k6.io/k6",
		"Version": "v0.40.0",
		"Time": "2022-09-08T07:54:34Z"
	},
	"Dir": "/go/pkg/mod/go.k6.io/k6@v0.33.1-0.20210825161650-c932a28ff940",
	"GoMod": "/go/pkg/mod/cache/download/go.k6.io/k6/@v/v0.33.1-0.20210825161650-c932a28ff940.mod",
	"GoVersion": "1.16"
}
```

I guess we can compare the `Time` or semver-compare the `Version` attributed between the main object and `Update` :thinking: Or we can figure out some other way to detect newer k6 versions.

### LINKED ISSUE #236: xk6 build logs the wrong k6 version
When running the `xk6 build` command, the console logs a version for the base `k6` binary. However, this logged version is **incorrect** and does not match the version that is actually used to build the custom binary.

This is misleading and can cause significant confusion when trying to verify which version of `k6` an extension was built with.

### Expected Behavior
The `xk6 build` command should accurately log the specific version of `k6` that is being used as the base for the build.

### Actual Behavior
The command logs a `k6` version, but it is incorrect. The actual `k6` version used in the final binary is different from the version number printed in the log output.

### Analysis
This issue appears to stem from the underlying `k6foundry` library. The incorrect version is likely reported when the library receives the default `k6` repository URL as the "replacement" `k6` repository parameter. The logic for determining the version seems to fail in this specific case, leading it to output an incorrect value.

### Workaround
A functional workaround in the code is to pass an empty string (`""`) as the replacement `k6` repository parameter, instead of passing the default repository URL. This appears to force the library to correctly determine and log the `k6` version being used.

### Fix

This bug has been fixed in `k6foundry` **v0.4.7**

To resolve this issue in `xk6`, the `k6foundry` dependency should be updated to **v0.4.7**

### PR DESCRIPTION
**Pull request by szkiba**
- Updates the `k6foundry` dependency to **v0.4.7**. This resolves a bug where the `xk6 build` command would log an incorrect version of `k6`.
- Warning logging if not the latest k6 version was used for the build

Closes #52 
Closes #236

### CODE REVIEW

File: internal/cmd/build_helper.go [hunk 1]
```diff
@@ -132,11 +132,14 @@ func newFoundry(ctx context.Context, opts *buildOptions) (k6foundry.Foundry, err
 			CopyGoEnv: true,
 			Env:       env,
 		},
-		K6Repo:      opts.k6repo,
 		SkipCleanup: opts.skipCleanup != 0,
 		Logger:      logger,
 	}
 
+	if opts.k6repo != defaultK6Repo { // only set if different from default: k6foundry workaround
```
Comment (pablochacin) [inline internal/cmd/build_helper.go:139]: Alternatively, we could make the default **k6 replacement** repository (this is how the parameter is defined in `k6foundry`) as `""`, unless there's a reason for using k6's repo as a default replacement repo. Then this won't be necessary.
