### PR TITLE
fix: "build" command on Windows

### LINKED ISSUE #473: xk6 build fails to build k6 on Windows
On Windows, `xk6 build` fails because the go subprocess it launches tries to create its work directory inside `C:\Windows\` (a protected system directory) instead of the user's temp directory. The parent process's `TMP`/`TEMP` are set correctly, and k6foundry itself uses the correct temp path — only the spawned go command is affected.

## Environment
* xk6 version: **xk6 version 1.3.7**
* Go version: **go version go1.26.2 windows/amd64**
* OS: Windows 11 Pro 10.0.26200
* Architecture: amd64
* Shell: PowerShell
* Running as: standard user (non-admin)

## Environment variables in the shell used to run xk6:
```powershell
PS C:\Users\andre\Development\xk6> $env:TMP
C:\Users\andre\AppData\Local\Temp
PS C:\Users\andre\Development\xk6> $env:TEMP
C:\Users\andre\AppData\Local\Temp
PS C:\Users\andre\Development\xk6> $env:GOTMPDIR
(empty)
```
## Steps to reproduce
1. Build xk6 on Windows (go install go.k6.io/xk6/cmd/xk6@v1.3.7).
2. From a writable working directory, run:
```powershell
.\xk6 build --verbose --with github.com/grafana/xk6-faker@latest
```
**Expected behavior**
xk6 builds a k6 binary with the xk6-faker extension in the current directory.
**Actual behavior**
```
> ./xk6 build --verbose --with github.com/grafana/xk6-faker@latest
5:30PM INF Building new k6 binary (native)
5:30PM INF Initializing Go module
go: creating new go.mod: module k6
5:30PM INF Creating k6 main
5:30PM INF adding dependency go.k6.io/k6@latest
5:30PM INF importing extensions
5:30PM INF adding dependency github.com/grafana/xk6-faker@latest
5:30PM INF Building k6
go: creating work dir: mkdir C:\Windows\go-build2288887796: Access is denied.
5:30PM INF Cleaning up work directory C:\Users\andre\AppData\Local\Temp\k6foundry3099781253
5:30PM ERR compiling: executing go command: exit status 1
```

## Suspected root cause
The two paths in the log are inconsistent:
* k6foundry correctly uses `C:\Users\andre\AppData\Local\Temp\k6foundry...` (inherits the parent process env).
The go subprocess uses `C:\Windows\go-build...` (ends up in the Windows directory).
* On Windows, when `TEMP`, `TMP`, and `USERPROFILE` are all unset/empty, Go's `os.TempDir()` falls back to `GetWindowsDirectory()`, which returns `C:\Windows`. See [`src/os/file_windows.go`](`https://github.com/golang/go/blob/master/src/os/file_windows.go`) — `tempDir()` checks `TMP`, then `TEMP`, then `USERPROFILE`, then falls back to `GetWindowsDirectory()`.

That strongly suggests xk6 (or its use of k6foundry) launches the go subprocess with a scrubbed or empty environment — likely with `CopyGoEnv: false` and no explicit `TEMP`/`TMP` added to [`k6foundry.GoOpts.Env`](https://pkg.go.dev/github.com/grafana/k6foundry#GoOpts). With an empty env, the Go child can't find any user temp dir and falls back to `C:\Windows`, which fails because standard users can't write there.

This doesn't reproduce on Linux/macOS because the equivalent `os.TempDir()` fallback there is `/tmp`, which is world-writable.

### PR DESCRIPTION
**Pull request by szkiba**
Closes #473

### CODE REVIEW

File: internal/cmd/build_helper.go [hunk 1]
```diff
@@ -65,6 +65,10 @@ var nonGoEnvToCopy = []string{ //nolint:gochecknoglobals
 	"GIT_SSH",             // to pass custom ssh options (legacy)
 	"GH_TOKEN",            // GitHub token for GitHub CLI as credential helper
 	"GITHUB_TOKEN",        // GitHub token for GitHub CLI as credential helper
+	"TMPDIR",              // required by git for temporary files
+	"TEMP",                // required by git for temporary files on Windows
+	"TMP",                 // required by git for temporary files on Windows
+
```
Comment (mstoykov) [inline internal/cmd/build_helper.go]:
```suggestion
```

**Review by mstoykov — APPROVED** [review]
